/* Generated By:JJTree: Do not edit this line. ASTaddExpressionDef.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTaddExpressionDef extends SimpleNode {
  public ASTaddExpressionDef(int id) {
    super(id);
  }

  public ASTaddExpressionDef(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2dfe5d9cf81d29db95b33b1ff6e43c9a (do not edit this line) */
