/* Generated By:JJTree: Do not edit this line. ASTbinaryExpressionEqDef.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTbinaryExpressionEqDef extends SimpleNode {
  public ASTbinaryExpressionEqDef(int id) {
    super(id);
  }

  public ASTbinaryExpressionEqDef(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ecdce511ad963f3581387f64c1335257 (do not edit this line) */
