/* Generated By:JJTree: Do not edit this line. ASTbinaryBoolExpressionAndDef.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTbinaryBoolExpressionAndDef extends SimpleNode {
  public ASTbinaryBoolExpressionAndDef(int id) {
    super(id);
  }

  public ASTbinaryBoolExpressionAndDef(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c23a76adc9e04e8cac064197c73273e7 (do not edit this line) */
