/* Generated By:JJTree: Do not edit this line. ASTbinaryBoolOperatorCompareDef.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTbinaryBoolOperatorCompareDef extends SimpleNode {
  public ASTbinaryBoolOperatorCompareDef(int id) {
    super(id);
  }

  public ASTbinaryBoolOperatorCompareDef(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8846c404ecb4495dc68be839203e7687 (do not edit this line) */
