/* Generated By:JJTree: Do not edit this line. ASTbinaryBoolExpressionCompareDef.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTbinaryBoolExpressionCompareDef extends SimpleNode {
  public ASTbinaryBoolExpressionCompareDef(int id) {
    super(id);
  }

  public ASTbinaryBoolExpressionCompareDef(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5530ca5a35c2cb2a316786aa5bbde077 (do not edit this line) */
