/* Generated By:JJTree: Do not edit this line. ASTcallFunction.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTcallFunction extends SimpleNode {
  public ASTcallFunction(int id) {
    super(id);
  }

  public ASTcallFunction(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=89b738ba6d39b661fdb05512b0c0157d (do not edit this line) */
