/* Generated By:JJTree: Do not edit this line. ASTIfStatementDef.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIfStatementDef extends SimpleNode {
  public ASTIfStatementDef(int id) {
    super(id);
  }

  public ASTIfStatementDef(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0a6c3e7fb8c8f8d76bbfbd2466ea84ef (do not edit this line) */
