/* Generated By:JJTree: Do not edit this line. ASTStatementBlockDef.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStatementBlockDef extends SimpleNode {
  public ASTStatementBlockDef(int id) {
    super(id);
  }

  public ASTStatementBlockDef(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e3bd809eea497f79807616e2a219fb49 (do not edit this line) */
