/* Generated By:JJTree: Do not edit this line. ASTStatementDef.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStatementDef extends SimpleNode {
  public ASTStatementDef(int id) {
    super(id);
  }

  public ASTStatementDef(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ee1ae0dc7ba64dc4943ac2ed6483a339 (do not edit this line) */
