/* Generated By:JJTree: Do not edit this line. ASTvarAssignDefInInit.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTvarAssignDefInInit extends SimpleNode {
  public ASTvarAssignDefInInit(int id) {
    super(id);
  }

  public ASTvarAssignDefInInit(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=db6296e205fa26179ab170427bf4f100 (do not edit this line) */
