/* Generated By:JJTree: Do not edit this line. ASTvarAssignDef.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTvarAssignDef extends SimpleNode {
  public ASTvarAssignDef(int id) {
    super(id);
  }

  public ASTvarAssignDef(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c965b000b368db61f6faede2a9b49bc1 (do not edit this line) */
