/* Generated By:JJTree: Do not edit this line. ASTvarDefineDef.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTvarDefineDef extends SimpleNode {
  public ASTvarDefineDef(int id) {
    super(id);
  }

  public ASTvarDefineDef(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c92ce106b1e9995f7e11f3d3f2bbcbab (do not edit this line) */
