/* Generated By:JJTree: Do not edit this line. ASTWhileStatementDef.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTWhileStatementDef extends SimpleNode {
  public ASTWhileStatementDef(int id) {
    super(id);
  }

  public ASTWhileStatementDef(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b69614e9f0e14a1925889a5c558a9902 (do not edit this line) */
